import { Component, HostListener, inject } from '@angular/core';
import { Router } from '@angular/router';
import { ReviewCardComponent } from '@components/review-card/review-card.component';
import { UserService } from '@services/api/user.service';
import { IReviewFullyPopulated } from 'app/shared/models/v2/review.schema';
import { ShinyMonstarTitleComponent } from 'app/shared/ui/shiny-monstar-title/shiny-monstar-title.component';
import { MessageService } from 'primeng/api';
import { DividerModule } from 'primeng/divider';
import { AuthGoogleButtonComponent } from './auth-google-button/auth-google-button.component';

@Component({
  selector: 'app-auth',
  standalone: true,
  imports: [
    AuthGoogleButtonComponent,
    ShinyMonstarTitleComponent,
    DividerModule,
    ReviewCardComponent,
  ],
  providers: [MessageService],
  templateUrl: './auth.component.html',
  styleUrl: './auth.component.scss',
})
export class AuthComponent {
  private userService = inject(UserService);
  private messageService = inject(MessageService);

  private router = inject(Router);

  showLeftPanel = window.innerWidth >= 1130;

  @HostListener('window:resize')
  onResize() {
    this.showLeftPanel = window.innerWidth >= 1130;
  }

  reviews: Array<IReviewFullyPopulated> = [
    {
      _id: '1',
      title: 'Great introduction to programming',
      description:
        'This unit is perfect for beginners. The lectures are engaging and the assignments help solidify concepts.',
      semester: 'First semester',
      grade: 'HD',
      year: 2024,
      overallRating: 4.5,
      relevancyRating: 5,
      facultyRating: 4,
      contentRating: 4.5,
      likes: 42,
      dislikes: 3,
      author: {
        _id: 'user1',
        email: 'abcd1234@student.monash.edu',
        username: 'Alex',
        isGoogleUser: true,
        googleID: 'google1',
        reviews: ['1'],
        admin: false,
        likedReviews: [],
        dislikedReviews: [],
        notifications: [],
      },
      createdAt: new Date('2024-06-15'),
      updatedAt: new Date('2024-06-15'),
      unit: {
        _id: 'u1',
        unitCode: 'FIT1045',
        name: 'Algorithms and Programming Fundamentals in Python',
        description: 'Introduction to programming concepts using Python.',
        avgOverallRating: 4.2,
        avgRelevancyRating: 4.5,
        avgFacultyRating: 4.0,
        avgContentRating: 4.3,
        level: 1,
        creditPoints: 6,
        school: 'Faculty of Information Technology',
        academicOrg: 'FIT',
        scaBand: '2',
        requisites: {
          permission: false,
          prohibitions: [],
          corequisites: [],
          prerequisites: [],
          cpRequired: 0,
        },
        offerings: [],
        tags: [],
        reviews: [],
      },
    },
    {
      _id: '2',
      title: 'Challenging but rewarding',
      description:
        'Data structures can be tough, but the tutors are incredibly helpful. Make sure to start assignments early!',
      semester: 'Second semester',
      grade: 'D',
      year: 2024,
      overallRating: 4,
      relevancyRating: 5,
      facultyRating: 4.5,
      contentRating: 4,
      likes: 28,
      dislikes: 5,
      author: {
        _id: 'user2',
        email: 'jsmith0042@student.monash.edu',
        username: 'Jordan',
        isGoogleUser: true,
        googleID: 'google2',
        reviews: ['2'],
        admin: false,
        likedReviews: [],
        dislikedReviews: [],
        notifications: [],
      },
      createdAt: new Date('2024-11-20'),
      updatedAt: new Date('2024-11-20'),
      unit: {
        _id: 'u2',
        unitCode: 'FIT2004',
        name: 'Algorithms and Data Structures',
        description: 'Advanced algorithms and data structures concepts.',
        avgOverallRating: 3.8,
        avgRelevancyRating: 4.8,
        avgFacultyRating: 4.2,
        avgContentRating: 4.0,
        level: 2,
        creditPoints: 6,
        school: 'Faculty of Information Technology',
        academicOrg: 'FIT',
        scaBand: '2',
        requisites: {
          permission: false,
          prohibitions: [],
          corequisites: [],
          prerequisites: [],
          cpRequired: 0,
        },
        offerings: [],
        tags: ['most-reviews'],
        reviews: [],
      },
    },
    {
      _id: '3',
      title: 'Excellent real-world applications',
      description:
        'Loved the group project! Working in a team environment prepared me well for industry. The agile methodology content was particularly useful.',
      semester: 'First semester',
      grade: 'HD',
      year: 2025,
      overallRating: 5,
      relevancyRating: 5,
      facultyRating: 4.5,
      contentRating: 5,
      likes: 56,
      dislikes: 2,
      author: {
        _id: 'user3',
        email: 'mlee5678@student.monash.edu',
        username: 'Morgan',
        isGoogleUser: true,
        googleID: 'google3',
        reviews: ['3'],
        admin: false,
        likedReviews: [],
        dislikedReviews: [],
        notifications: [],
      },
      createdAt: new Date('2025-06-10'),
      updatedAt: new Date('2025-06-10'),
      unit: {
        _id: 'u3',
        unitCode: 'FIT2101',
        name: 'Software Engineering Process',
        description: 'Team-based software development methodologies.',
        avgOverallRating: 4.5,
        avgRelevancyRating: 4.9,
        avgFacultyRating: 4.3,
        avgContentRating: 4.6,
        level: 2,
        creditPoints: 6,
        school: 'Faculty of Information Technology',
        academicOrg: 'FIT',
        scaBand: '2',
        requisites: {
          permission: false,
          prohibitions: [],
          corequisites: [],
          prerequisites: [],
          cpRequired: 0,
        },
        offerings: [],
        tags: ['wam-booster'],
        reviews: [],
      },
    },
    {
      _id: '4',
      title: 'Heavy workload but worth it',
      description:
        'The database concepts are essential for any developer. SQL assignments were practical and the exam was fair.',
      semester: 'Second semester',
      grade: 'D',
      year: 2024,
      overallRating: 4,
      relevancyRating: 4.5,
      facultyRating: 3.5,
      contentRating: 4.5,
      likes: 34,
      dislikes: 8,
      author: {
        _id: 'user4',
        email: 'kwon9012@student.monash.edu',
        username: 'Kim',
        isGoogleUser: true,
        googleID: 'google4',
        reviews: ['4'],
        admin: false,
        likedReviews: [],
        dislikedReviews: [],
        notifications: [],
      },
      createdAt: new Date('2024-12-01'),
      updatedAt: new Date('2024-12-01'),
      unit: {
        _id: 'u4',
        unitCode: 'FIT2094',
        name: 'Databases',
        description: 'Relational database design and SQL.',
        avgOverallRating: 3.9,
        avgRelevancyRating: 4.6,
        avgFacultyRating: 3.7,
        avgContentRating: 4.4,
        level: 2,
        creditPoints: 6,
        school: 'Faculty of Information Technology',
        academicOrg: 'FIT',
        scaBand: '2',
        requisites: {
          permission: false,
          prohibitions: [],
          corequisites: [],
          prerequisites: [],
          cpRequired: 0,
        },
        offerings: [],
        tags: [],
        reviews: [],
      },
    },
    {
      _id: '5',
      title: 'Mind-bending but fascinating',
      description:
        'Machine learning concepts are complex but the practical labs really help. Great preparation for AI careers.',
      semester: 'First semester',
      grade: 'C',
      year: 2025,
      overallRating: 3.5,
      relevancyRating: 5,
      facultyRating: 4,
      contentRating: 4,
      likes: 19,
      dislikes: 6,
      author: {
        _id: 'user5',
        email: 'rpat3456@student.monash.edu',
        username: 'Riley',
        isGoogleUser: true,
        googleID: 'google5',
        reviews: ['5'],
        admin: false,
        likedReviews: [],
        dislikedReviews: [],
        notifications: [],
      },
      createdAt: new Date('2025-05-22'),
      updatedAt: new Date('2025-05-22'),
      unit: {
        _id: 'u5',
        unitCode: 'FIT3181',
        name: 'Deep Learning',
        description: 'Neural networks and deep learning techniques.',
        avgOverallRating: 3.6,
        avgRelevancyRating: 4.7,
        avgFacultyRating: 3.9,
        avgContentRating: 4.1,
        level: 3,
        creditPoints: 6,
        school: 'Faculty of Information Technology',
        academicOrg: 'FIT',
        scaBand: '2',
        requisites: {
          permission: false,
          prohibitions: [],
          corequisites: [],
          prerequisites: [],
          cpRequired: 0,
        },
        offerings: [],
        tags: ['controversial'],
        reviews: [],
      },
    },
    {
      _id: '6',
      title: 'Essential for web developers',
      description:
        'Covers both frontend and backend development. The final project was challenging but I learned so much building a full-stack app.',
      semester: 'Second semester',
      grade: 'HD',
      year: 2024,
      overallRating: 4.5,
      relevancyRating: 5,
      facultyRating: 4.5,
      contentRating: 4.5,
      likes: 67,
      dislikes: 4,
      author: {
        _id: 'user6',
        email: 'tchen7890@student.monash.edu',
        username: 'Taylor',
        isGoogleUser: true,
        googleID: 'google6',
        reviews: ['6'],
        admin: false,
        likedReviews: [],
        dislikedReviews: [],
        notifications: [],
      },
      createdAt: new Date('2024-11-15'),
      updatedAt: new Date('2024-11-15'),
      unit: {
        _id: 'u6',
        unitCode: 'FIT2095',
        name: 'E-Business Software Technologies',
        description: 'Web application development with modern frameworks.',
        avgOverallRating: 4.4,
        avgRelevancyRating: 4.8,
        avgFacultyRating: 4.4,
        avgContentRating: 4.5,
        level: 2,
        creditPoints: 6,
        school: 'Faculty of Information Technology',
        academicOrg: 'FIT',
        scaBand: '2',
        requisites: {
          permission: false,
          prohibitions: [],
          corequisites: [],
          prerequisites: [],
          cpRequired: 0,
        },
        offerings: [],
        tags: ['most-reviews'],
        reviews: [],
      },
    },
  ];

  onGoogleCredential(idToken: string) {
    this.userService.googleAuthenticate(idToken).subscribe({
      next: () => this.router.navigate(['/list']),
      error: () =>
        this.messageService.add({
          severity: 'error',
          summary: 'Error signing in',
          detail: 'It did not work for some reason lol :()',
        }),
    });
  }
}
